### ISSUE TITLE
Can't use perms in templates without pre-caching

### ISSUE THREAD

**Issue by GriceTurrble** [dabapps/django-zen-queries#15]
I hit a gotcha while developing with zen_queries turned on that I think is worth mentioning in the docs.

Permission checks in Django are cached (see [here](https://docs.djangoproject.com/en/2.2/topics/auth/default/#permission-caching)), but the cache may not be populated yet by the time the template is being rendered. In that case, calling on `{{ perms.<permission> }}` from template code can cause zen_queries to blow up. Without a meaningful error message, that can be a bit difficult to track down.

A workaround is to pre-populate the cache by including a manual permission check in the view:

```python
request.user.has_perm('app.permission')
# returns True/False, which we ignore; but also caches user's permissions
return render(...)
```

It might also be worth adding a view decorator that would force permission caching at the start of the request (assuming the view doesn't change user permissions, which would require clearing and re-populating the cache).

**Comment by j4mie** [comment]
@GriceTurrble I've open a PR against the README - #17. I basically followed your suggestion but used `request.user.get_all_permissions()` instead, as it seemed more obvious than fetching some random permission. Are you happy with this approach?

**Comment by GriceTurrble** [comment]
Yes that does seem appropriate. Thank you. :)
