### ISSUE TITLE
Not compatible with DRF unpaginated ListAPIView

### ISSUE THREAD

**Issue by nvlaarhoven** [dabapps/django-zen-queries#18]
I tried to setup an unpaginated endpoint by setting `pagination_class = None` on the `ListAPIView` but this gave a `QueriesDisabledError`.

DRF evaluates the `queryset` earlier if you've got a pagination class.

I got around it by implementing a `NonePagination` class manually 

```
from rest_framework.pagination import BasePagination
from rest_framework.response import Response


class NonePagination(BasePagination):
    # Use this Pagination class for an unpaginated list.
    # Setting pagination_class to None will raise a QueriesDisabledError.
    def get_paginated_response(self, data):
        return Response(data)

    def paginate_queryset(self, queryset, request, view=None):
        return list(queryset)
```

If you don't have `return list(queryset)`, when `get_serializer` is called the initial query to get all the objects to serialize is done there instead.

Perhaps zen queries needs to target a different generic method to disable queries on.

**Comment by RealOrangeOne** [comment]
Fixed in #27
