### ISSUE TITLE
queries_disabled as decorator

### ISSUE THREAD

**Issue by SaturnFromTitan** [dabapps/django-zen-queries#24]
First off, thanks for the amazing package. I use it a lot and love it!

I find myself often writing functions like:

```
def validate_xyz(value):
    with queries_disabled():
        ...
```

Therefore it would be nice to have a decorator so that I can save one level of indent

```
@queries_disabled
def validate_xyz(value):
        ...
```

Do you think it's reasonable to add this? If so, I could take a look and work on a PR.

**Comment by j4mie** [comment]
It actually already does work like this! The `queries_disabled` function is decorated with `contextlib.contextmanager`: https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

> contextmanager() uses ContextDecorator so the context managers it creates can be used as decorators as well as in with statements.

You can also use it as a method decorator by using Django's `method_decorator` util.

I mentioned this in [the blog post](https://www.dabapps.com/blog/performance-issues-caused-by-django-implicit-database-queries/) which is linked from the README, but I realise it's not actually documented in the body of the README itself. I'd happy accept a patch which adds this in.

Thanks :)

**Comment by SaturnFromTitan** [comment]
Yes, you're right it's working! I'll submit a PR in the coming days :)
