### ISSUE TITLE
[Question] this is production ready right?

### ISSUE THREAD

**Issue by simkimsia** [dabapps/django-zen-queries#46]
Hi there, I'm asking because the last release was in July 2021 and typically i follow a heuristic of "if it's 1 year from last release, then that is a sign of no longer actively maintained".

I don't feel that's the case because the issues have been quickly and promptly answered. but I just want to ask explicitly.

**Comment by j4mie** [comment]
We're using it in production. It's definitely actively maintained, it's just a small library and so not much needed in the way of changes. I'll be opening a PR to add Django 4.1 beta to the test matrix soon.

**Comment by simkimsia** [comment]
Noted. I will tweak my own heuristic for this library.
